### ISSUE TITLE
Strange shrinking behaviour when shrinking horizontally

### ISSUE THREAD

**Issue by Sekerali** [LuisEscorza/GodotLabelFontAutoSizer#2]
Very insignificant issue, but might be worth looking into in case of potentially being related to another issue.

When shrinking the height while having a wide width, the text shrinks as much as possible as expected.

When shrinking the width while having a tall height, and having a small text count, the text does not shrink enough. Worst case, having a single letter does not shrink at all when reducing the width if the height remains tall enough. More text allows more width shrinking.

**Comment by LuisEscorza** [comment]
I see, I'll check that out, thanks!

**Comment by LuisEscorza** [comment]
Alright, this I was able to reproduce :)

The issue is that with normal `Label` nodes, I'm using `get_line_count()`   and `get_visible_line_count()`, which are the only options provided by godot (I'm sure there are other ways way more intricate, a lot less performant), and in the case you propose, "in theory" there shouldn't be a need to resize, since there is an equal amount of lines in the text against the amount of lines that are visible. So, as this is as this would be a very unusual scenario for any user, I'd rather leave it as is, before trying to refactor the whole thing with more complex checks, which might be worse for performance.

Luckily, for `RichTextLabel` nodes, we do have other methods available, and I was able to fix it by also checking the width of the content not just the height, so in the case there's someone that in that situation, a Rich Text Label can be used without issues 👌

In some hours I'll have a new release ready for download, thanks!

Edit: this change was only possible in the Godot 4 version, so unfortunately the bug will remain in 3.x
